### ISSUE TITLE
[공통] CSS Styling

### ISSUE THREAD

**Issue by hhhyyo** [kkdd0757/Time_Yamyam#17]
- [ ] normalize css 적용

- [x] 공통 color 설정
        1) scss root에 색상 추가 (메인 컬러와 주로 쓰는 색상)
- [x] 공통 여백 설정
        1) margin, padding 

- [ ] 유저 에이전트 스타일 초기화 (버튼, ul, li 등)

**Comment by dbstjrrb12** [comment]
확인했습니다
