### ISSUE TITLE
[공통][메뉴바] 이동기능

### ISSUE THREAD

**Issue by hhhyyo** [kkdd0757/Time_Yamyam#28]
- [x] 홈 클릭 시 메인페이지로 이동
- [x] 스터디 그룹 만들기 클릭 시 스터디 그룹 만들기 페이지로 이동
- [x] 마이페이지 클릭 시 마이페이지로 이동
- [x] 인증올리기 클릭 시 인증올리기 페이지로 이동
- [x] 알림 클릭 시 알림으로 이동

**Comment by hanana1253** [comment]
확인했습니다.

**Comment by dbstjrrb12** [comment]
확인했습니다
