### ISSUE TITLE
[공통][로그인 기능] toggle 기능

### ISSUE THREAD

**Issue by dbstjrrb12** [kkdd0757/Time_Yamyam#8]
- [x] login.scss 내에 toggle 클래스 스타일 적용 
- [x] login.html 내에 회원가입 마크업(<main> 태그) 내에 hidden 클래스 추가 
- [x] login.js에 회원가입 앵커 태그 이벤트 등록하여 hidden 클래스 추가 및 삭제 기능 구현

**Comment by hhhyyo** [comment]
확인했습니다
